const randomArtists = [
  'The Beatles',
  'Bob Dylan',
  'Elvis Presley',
  'The Rolling Stones',
  'Aretha Franklin',
  'Jimi Hendrix',
  'David Bowie',
  'Pink Floyd',
  'Led Zeppelin',
  'The Who',
  'James Brown',
  'Stevie Wonder',
  'Marvin Gaye',
  'Michael Jackson',
  'Madonna',
  'Prince',
  'U2',
  'Nirvana',
  'Queen',
  'Johnny Cash',
  'The Beach Boys',
  'The Clash',
  'The Ramones',
  'Public Enemy',
  'Bob Marley',
  'The Grateful Dead',
  'Metallica',
  'Beyonce',
  'Jay-Z',
  'Kanye West',
  'Radiohead',
  'Elton John',
  'Janis Joplin',
  'AC/DC',
  'The Velvet Underground',
  'Miles Davis',
  'The Doors',
  'Tupac Shakur',
  'The Notorious B.I.G.',
  'Eminem',
  'OutKast',
  'Coldplay',
  'Aerosmith',
  'The Smiths',
  'R.E.M.',
  'Fleetwood Mac',
  'ABBA',
  'Rihanna',
  'Taylor Swift',
  'Kendrick Lamar',
  'Bruce Springsteen',
  'Simon & Garfunkel',
  'The Cure',
  'Depeche Mode',
  'Bjork',
  'Lady Gaga',
  'Pearl Jam',
  'Sade',
  'Phil Collins',
  'Whitney Houston',
  'The Police',
  'Black Sabbath',
  'The Kinks',
  'Ozzy Osbourne',
  'Amy Winehouse',
  'Frank Zappa',
  'Billy Joel',
  'John Lennon',
  'Paul McCartney',
  'Sonic Youth',
  'Green Day',
  'Sex Pistols',
  'Diana Ross',
  'Lauryn Hill',
  'Dr. Dre',
  'Snoop Dogg',
  'The Eagles',
  'T. Rex',
  'Nina Simone',
  'Patti Smith',
  'Blondie',
  'Red Hot Chili Peppers',
  'Pavement',
  'Nine Inch Nails',
  'Aaliyah',
  'Joni Mitchell',
  'Neil Young',
  'Eric Clapton',
  'The Flaming Lips',
  'Pet Shop Boys',
  'Rush',
  "Guns N' Roses",
  'N.W.A',
  'LL Cool J',
  'Mariah Carey',
  'Nick Cave',
];

export default randomArtists;
